language: node_js
node_js:
- 14
cache: yarn
script:
- yarn lint
- yarn test
deploy:
  provider: heroku
  api_key:
    secure: eVmR6mzVA2BBZQUuOYMv6zV2lMdDl5yv6yihri941GvBnADSKHcWVzwGFFfvWeG5jG5aynNHYcrzd7Kjw+Qf2RtphEswouzKBhwqYBJmnIOrqb2JW7ZwGEncw4DxnLb8WXLYcKJc41C08I8dB1YLuFC1BE8LZ0RdmNZNwCcGVr/3Wj+IuxTRzbKfPNLRKZ27v18btwgqkhCJRK7Q6AJjfFNA1uRyHnptKjv76Z4UO00FwQtBCERRmTeE7R8KlxZ/Te94/3DC6/y8MZ/LI6gx+h7vK/steJGdBhNeJhYaiPfKewLCWK2UjP+DG5zIGvstlqOHiDkXSa9DKzAyA83Qb0EaSabu5msxaNFKaoPu5s8YoFv500kHUHqbpW8Aw8wTmOHcZeV44MrqFIP4mODl5fqKB7alN1BnuZfyjlzrfohqqgjHfTeRoKtR1IjH9WLNq5BuUs9OfvD/LOysyaXCF1Rju1u7DSzptYjp/owtfs4GtrXefBmixxvvTvsx6lpq/MLZmEMQp6HNZs6rHDVutg9gGhQGpNrs0PrQurnTpdirhp77xCs0KqrFTWD6AV/MCHe2/kpVkvpZbx8KBWkM+BAs+NYc8zwmqw6bP9cjdqFVzhG93/Y/jMG7wMncLy/ZKI1veU2pHtHYcp4542WyU+T5Yu/ptOckjCND3hamvS4=
  app: asteffey-file-metadata
  on:
    repo: asteffey/fcc-file-metadata-microservice
  skip_cleanup: true
